services:
  tirsvad-cli:
    build:
      context: .
      dockerfile: Dockerfile
    image: tirsvad/tirsvadcli_debian13_dotnet10:latest
    container_name: tirsvadcli_debian13_dotnet10
    tty: true
    stdin_open: true
